In [48]:
import tensorflow as tf
from sklearn import datasets
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# load iris dataset
iris = datasets.load_iris()
iris_df=pd.DataFrame(iris.data)
iris_df['class']=iris.target

iris_df.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class']
iris_df.dropna(how="all", inplace=True) # remove any empty lines

iris_X=iris_df.iloc[:,[0,1,2,3]].values
iris_Y=iris_df.iloc[:,4].values
#print(iris_X)
#print(iris_Y)

print(iris_X[0:5])
print(iris_Y[0:5])

print(iris_X.shape)
print(iris_Y.shape)

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(iris_Y)
Y = pd.get_dummies(y1).values

print(y1)
print(Y[0:5])

X_train, X_test, y_train, y_test = train_test_split(iris_X, Y, test_size=0.2, random_state=0)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
(150, 4)
(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [49]:

print(X_train[0:5])
print(y_train[0:5])
print(X_test[0:5])
print(y_test[0:5])

model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])
model

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, batch_size=50, epochs=100, validation_steps=1)


[[6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]]
[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]]
[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]]
[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]]
Epoch 1/100
3/3 [==============================] - 2s 15ms/step - loss: 1.1507 - accuracy: 0.2083
Epoch 2/100
3/3 [==============================] - 0s 6ms/step - loss: 1.0574 - accuracy: 0.1417
Epoch 3/100
3/3 [==============================] - 0s 11ms/step - loss: 1.0072 - accuracy: 0.3417
Epoch 4/100
3/3 [==============================] - 0s 10ms/step - loss: 0.9769 - accuracy: 0.2250
Epoch 5/100
3/3 [==============================] - 0s 18ms/step - loss: 0.9537 - accuracy: 0.3167
Epoch 6/100
3/3 [==============================] - 0s 40ms/step - loss: 0.9376 - accuracy: 0.3833
Epoch 7/100
3/3 [==============================] - 0s 8ms/step - loss: 0.9258 - accuracy: 0.5000
Epoch 8/100
3/3 [===============

In [50]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.3708459138870239
Test accuracy: 0.9666666388511658


In [51]:
y_pred = model.predict(X_test)
y_pred

actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

1/1 [==============================] - 0s 104ms/step
Actual: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Predicted: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 2 0 0 2 0 0 1 1 0]
